name: flaming_problem
description: Up in flames
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flame: ^1.8.2
  flutter:
    sdk: flutter

dev_dependencies:
  flame_lint: ^1.1.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true